language: node_js
sudo: required
node_js:
  - "8.9"
  - "9.4"
script:
  - yarn lint
  - yarn test
cache: yarn
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
